# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64

dependencies:
 - joblib
 - pandas
 - matplotlib
 - pydot
 - scikit-learn
 - tensorflow
 - comet_ml::comet_ml
 - plotly::plotly
 - plotly::plotly-orca
 - conda-forge::treelib
 - conda-forge::shap



